export { About } from './About'
export { Categories } from './Categories'
export { Contact } from './Contact'
export { Hero } from './Hero'
export { Locations } from './Locations'
export { PromoStrip } from './PromoStrip'
